spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3307/inventory_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082
