spring:
  application:
    name: inventory-service

  datasource:
    url: ${INVENTORY_SERVICE_DATABASE_URL}
    username: ${INVENTORY_SERVICE_DATABASE_USERNAME}
    password: ${INVENTORY_SERVICE_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082
